# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (3, 0, 0):
    new_instancemethod = lambda func, inst, cls: _GCE2d.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_GCE2d', [dirname(__file__)])
        except ImportError:
            import _GCE2d
            return _GCE2d
        if fp is not None:
            try:
                _mod = imp.load_module('_GCE2d', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _GCE2d = swig_import_helper()
    del swig_import_helper
else:
    import _GCE2d
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


class SwigPyIterator(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _GCE2d.delete_SwigPyIterator
    def __iter__(self):
        return self
SwigPyIterator.value = new_instancemethod(_GCE2d.SwigPyIterator_value, None, SwigPyIterator)
SwigPyIterator.incr = new_instancemethod(_GCE2d.SwigPyIterator_incr, None, SwigPyIterator)
SwigPyIterator.decr = new_instancemethod(_GCE2d.SwigPyIterator_decr, None, SwigPyIterator)
SwigPyIterator.distance = new_instancemethod(_GCE2d.SwigPyIterator_distance, None, SwigPyIterator)
SwigPyIterator.equal = new_instancemethod(_GCE2d.SwigPyIterator_equal, None, SwigPyIterator)
SwigPyIterator.copy = new_instancemethod(_GCE2d.SwigPyIterator_copy, None, SwigPyIterator)
SwigPyIterator.next = new_instancemethod(_GCE2d.SwigPyIterator_next, None, SwigPyIterator)
SwigPyIterator.__next__ = new_instancemethod(_GCE2d.SwigPyIterator___next__, None, SwigPyIterator)
SwigPyIterator.previous = new_instancemethod(_GCE2d.SwigPyIterator_previous, None, SwigPyIterator)
SwigPyIterator.advance = new_instancemethod(_GCE2d.SwigPyIterator_advance, None, SwigPyIterator)
SwigPyIterator.__eq__ = new_instancemethod(_GCE2d.SwigPyIterator___eq__, None, SwigPyIterator)
SwigPyIterator.__ne__ = new_instancemethod(_GCE2d.SwigPyIterator___ne__, None, SwigPyIterator)
SwigPyIterator.__iadd__ = new_instancemethod(_GCE2d.SwigPyIterator___iadd__, None, SwigPyIterator)
SwigPyIterator.__isub__ = new_instancemethod(_GCE2d.SwigPyIterator___isub__, None, SwigPyIterator)
SwigPyIterator.__add__ = new_instancemethod(_GCE2d.SwigPyIterator___add__, None, SwigPyIterator)
SwigPyIterator.__sub__ = new_instancemethod(_GCE2d.SwigPyIterator___sub__, None, SwigPyIterator)
SwigPyIterator_swigregister = _GCE2d.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

import OCC.gp
import OCC.Standard
import OCC.Geom2d
import OCC.MMgt
import OCC.GeomAbs
import OCC.TColgp
import OCC.TCollection
import OCC.TColStd
import OCC.gce
class GCE2d_MakeMirror(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :param Point:
        :type Point: gp_Pnt2d
        :rtype: None

        :param Axis:
        :type Axis: gp_Ax2d
        :rtype: None

        :param Line:
        :type Line: gp_Lin2d
        :rtype: None

        * Make a symetry transformation af axis defined by <Point> and <Direc>.

        :param Point:
        :type Point: gp_Pnt2d
        :param Direc:
        :type Direc: gp_Dir2d
        :rtype: None

        """
        _GCE2d.GCE2d_MakeMirror_swiginit(self, _GCE2d.new_GCE2d_MakeMirror(*args))

    def Value(self, *args):
        """
        * Returns the constructed transformation.

        :rtype: Handle_Geom2d_Transformation

        """
        return _GCE2d.GCE2d_MakeMirror_Value(self, *args)


    def Operator(self, *args):
        """
        :rtype: Handle_Geom2d_Transformation

        """
        return _GCE2d.GCE2d_MakeMirror_Operator(self, *args)


    def __del__(self):
    	try:
    		self.thisown = False
    		GarbageCollector.garbage.collect_object(self)
    	except:
    		pass


GCE2d_MakeMirror.Value = new_instancemethod(_GCE2d.GCE2d_MakeMirror_Value, None, GCE2d_MakeMirror)
GCE2d_MakeMirror.Operator = new_instancemethod(_GCE2d.GCE2d_MakeMirror_Operator, None, GCE2d_MakeMirror)
GCE2d_MakeMirror._kill_pointed = new_instancemethod(_GCE2d.GCE2d_MakeMirror__kill_pointed, None, GCE2d_MakeMirror)
GCE2d_MakeMirror_swigregister = _GCE2d.GCE2d_MakeMirror_swigregister
GCE2d_MakeMirror_swigregister(GCE2d_MakeMirror)

class GCE2d_MakeRotation(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        * Constructs a rotation through angle Angle about the center Point.

        :param Point:
        :type Point: gp_Pnt2d
        :param Angle:
        :type Angle: float
        :rtype: None

        """
        _GCE2d.GCE2d_MakeRotation_swiginit(self, _GCE2d.new_GCE2d_MakeRotation(*args))

    def Value(self, *args):
        """
        * Returns the constructed transformation.

        :rtype: Handle_Geom2d_Transformation

        """
        return _GCE2d.GCE2d_MakeRotation_Value(self, *args)


    def Operator(self, *args):
        """
        :rtype: Handle_Geom2d_Transformation

        """
        return _GCE2d.GCE2d_MakeRotation_Operator(self, *args)


    def __del__(self):
    	try:
    		self.thisown = False
    		GarbageCollector.garbage.collect_object(self)
    	except:
    		pass


GCE2d_MakeRotation.Value = new_instancemethod(_GCE2d.GCE2d_MakeRotation_Value, None, GCE2d_MakeRotation)
GCE2d_MakeRotation.Operator = new_instancemethod(_GCE2d.GCE2d_MakeRotation_Operator, None, GCE2d_MakeRotation)
GCE2d_MakeRotation._kill_pointed = new_instancemethod(_GCE2d.GCE2d_MakeRotation__kill_pointed, None, GCE2d_MakeRotation)
GCE2d_MakeRotation_swigregister = _GCE2d.GCE2d_MakeRotation_swigregister
GCE2d_MakeRotation_swigregister(GCE2d_MakeRotation)

class GCE2d_MakeScale(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        * Constructs a scaling transformation with - Point as the center of the transformation, and - Scale as the scale factor.

        :param Point:
        :type Point: gp_Pnt2d
        :param Scale:
        :type Scale: float
        :rtype: None

        """
        _GCE2d.GCE2d_MakeScale_swiginit(self, _GCE2d.new_GCE2d_MakeScale(*args))

    def Value(self, *args):
        """
        * Returns the constructed transformation.

        :rtype: Handle_Geom2d_Transformation

        """
        return _GCE2d.GCE2d_MakeScale_Value(self, *args)


    def Operator(self, *args):
        """
        :rtype: Handle_Geom2d_Transformation

        """
        return _GCE2d.GCE2d_MakeScale_Operator(self, *args)


    def __del__(self):
    	try:
    		self.thisown = False
    		GarbageCollector.garbage.collect_object(self)
    	except:
    		pass


GCE2d_MakeScale.Value = new_instancemethod(_GCE2d.GCE2d_MakeScale_Value, None, GCE2d_MakeScale)
GCE2d_MakeScale.Operator = new_instancemethod(_GCE2d.GCE2d_MakeScale_Operator, None, GCE2d_MakeScale)
GCE2d_MakeScale._kill_pointed = new_instancemethod(_GCE2d.GCE2d_MakeScale__kill_pointed, None, GCE2d_MakeScale)
GCE2d_MakeScale_swigregister = _GCE2d.GCE2d_MakeScale_swigregister
GCE2d_MakeScale_swigregister(GCE2d_MakeScale)

class GCE2d_MakeTranslation(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        * Constructs a translation along the vector Vect.

        :param Vect:
        :type Vect: gp_Vec2d
        :rtype: None

        * Constructs a translation along the vector (Point1,Point2) defined from the point Point1 to the point Point2.

        :param Point1:
        :type Point1: gp_Pnt2d
        :param Point2:
        :type Point2: gp_Pnt2d
        :rtype: None

        """
        _GCE2d.GCE2d_MakeTranslation_swiginit(self, _GCE2d.new_GCE2d_MakeTranslation(*args))

    def Value(self, *args):
        """
        * Returns the constructed transformation.

        :rtype: Handle_Geom2d_Transformation

        """
        return _GCE2d.GCE2d_MakeTranslation_Value(self, *args)


    def Operator(self, *args):
        """
        :rtype: Handle_Geom2d_Transformation

        """
        return _GCE2d.GCE2d_MakeTranslation_Operator(self, *args)


    def __del__(self):
    	try:
    		self.thisown = False
    		GarbageCollector.garbage.collect_object(self)
    	except:
    		pass


GCE2d_MakeTranslation.Value = new_instancemethod(_GCE2d.GCE2d_MakeTranslation_Value, None, GCE2d_MakeTranslation)
GCE2d_MakeTranslation.Operator = new_instancemethod(_GCE2d.GCE2d_MakeTranslation_Operator, None, GCE2d_MakeTranslation)
GCE2d_MakeTranslation._kill_pointed = new_instancemethod(_GCE2d.GCE2d_MakeTranslation__kill_pointed, None, GCE2d_MakeTranslation)
GCE2d_MakeTranslation_swigregister = _GCE2d.GCE2d_MakeTranslation_swigregister
GCE2d_MakeTranslation_swigregister(GCE2d_MakeTranslation)

class GCE2d_Root(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def IsDone(self, *args):
        """
        * Returns true if the construction is successful.

        :rtype: bool

        """
        return _GCE2d.GCE2d_Root_IsDone(self, *args)


    def Status(self, *args):
        """
        * Returns the status of the construction - gce_Done, if the construction is successful, or - another value of the gce_ErrorType enumeration indicating why the construction failed.

        :rtype: gce_ErrorType

        """
        return _GCE2d.GCE2d_Root_Status(self, *args)


    def __init__(self):
        _GCE2d.GCE2d_Root_swiginit(self, _GCE2d.new_GCE2d_Root())

    def __del__(self):
    	try:
    		self.thisown = False
    		GarbageCollector.garbage.collect_object(self)
    	except:
    		pass


GCE2d_Root.IsDone = new_instancemethod(_GCE2d.GCE2d_Root_IsDone, None, GCE2d_Root)
GCE2d_Root.Status = new_instancemethod(_GCE2d.GCE2d_Root_Status, None, GCE2d_Root)
GCE2d_Root._kill_pointed = new_instancemethod(_GCE2d.GCE2d_Root__kill_pointed, None, GCE2d_Root)
GCE2d_Root_swigregister = _GCE2d.GCE2d_Root_swigregister
GCE2d_Root_swigregister(GCE2d_Root)

class GCE2d_MakeArcOfCircle(GCE2d_Root):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        * Makes an arc of circle (TrimmedCurve from Geom2d) from a circle between two parameters Alpha1 and Alpha2. The two parameters are angles. The parameters are in radians.

        :param Circ:
        :type Circ: gp_Circ2d
        :param Alpha1:
        :type Alpha1: float
        :param Alpha2:
        :type Alpha2: float
        :param Sense: default value is Standard_True
        :type Sense: bool
        :rtype: None

        * Makes an arc of circle (TrimmedCurve from Geom2d) from a circle between point <P> and the parameter Alpha. Alpha is given in radians.

        :param Circ:
        :type Circ: gp_Circ2d
        :param P:
        :type P: gp_Pnt2d
        :param Alpha:
        :type Alpha: float
        :param Sense: default value is Standard_True
        :type Sense: bool
        :rtype: None

        * Makes an arc of circle (TrimmedCurve from Geom2d) from a circle between two points P1 and P2.

        :param Circ:
        :type Circ: gp_Circ2d
        :param P1:
        :type P1: gp_Pnt2d
        :param P2:
        :type P2: gp_Pnt2d
        :param Sense: default value is Standard_True
        :type Sense: bool
        :rtype: None

        * Makes an arc of circle (TrimmedCurve from Geom2d) from three points P1,P2,P3 between two points P1 and P3, and passing through the point P2.

        :param P1:
        :type P1: gp_Pnt2d
        :param P2:
        :type P2: gp_Pnt2d
        :param P3:
        :type P3: gp_Pnt2d
        :rtype: None

        * Makes an arc of circle (TrimmedCurve from Geom2d) from two points P1,P2 and the tangente to the solution at the point P1.

        :param P1:
        :type P1: gp_Pnt2d
        :param V:
        :type V: gp_Vec2d
        :param P2:
        :type P2: gp_Pnt2d
        :rtype: None

        """
        _GCE2d.GCE2d_MakeArcOfCircle_swiginit(self, _GCE2d.new_GCE2d_MakeArcOfCircle(*args))

    def Value(self, *args):
        """
        * Returns the constructed arc of circle. Exceptions StdFail_NotDone if no arc of circle is constructed.

        :rtype: Handle_Geom2d_TrimmedCurve

        """
        return _GCE2d.GCE2d_MakeArcOfCircle_Value(self, *args)


    def Operator(self, *args):
        """
        :rtype: Handle_Geom2d_TrimmedCurve

        """
        return _GCE2d.GCE2d_MakeArcOfCircle_Operator(self, *args)


    def __del__(self):
    	try:
    		self.thisown = False
    		GarbageCollector.garbage.collect_object(self)
    	except:
    		pass


GCE2d_MakeArcOfCircle.Value = new_instancemethod(_GCE2d.GCE2d_MakeArcOfCircle_Value, None, GCE2d_MakeArcOfCircle)
GCE2d_MakeArcOfCircle.Operator = new_instancemethod(_GCE2d.GCE2d_MakeArcOfCircle_Operator, None, GCE2d_MakeArcOfCircle)
GCE2d_MakeArcOfCircle._kill_pointed = new_instancemethod(_GCE2d.GCE2d_MakeArcOfCircle__kill_pointed, None, GCE2d_MakeArcOfCircle)
GCE2d_MakeArcOfCircle_swigregister = _GCE2d.GCE2d_MakeArcOfCircle_swigregister
GCE2d_MakeArcOfCircle_swigregister(GCE2d_MakeArcOfCircle)

class GCE2d_MakeArcOfEllipse(GCE2d_Root):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        * Make an arc of Ellipse (TrimmedCurve from Geom2d) from a Ellipse between two parameters Alpha1 and Alpha2.

        :param Elips:
        :type Elips: gp_Elips2d
        :param Alpha1:
        :type Alpha1: float
        :param Alpha2:
        :type Alpha2: float
        :param Sense: default value is Standard_True
        :type Sense: bool
        :rtype: None

        * Make an arc of Ellipse (TrimmedCurve from Geom2d) from a Ellipse between point <P> and the parameter Alpha.

        :param Elips:
        :type Elips: gp_Elips2d
        :param P:
        :type P: gp_Pnt2d
        :param Alpha:
        :type Alpha: float
        :param Sense: default value is Standard_True
        :type Sense: bool
        :rtype: None

        * Make an arc of Ellipse (TrimmedCurve from Geom2d) from a Ellipse between two points P1 and P2. Please, note: The orientation of the arc is: - the trigonometric sense if Sense is not defined or is true (default value), or - the opposite sense if Sense is false. - Alpha1, Alpha2 and Alpha are angle values, given in radians. - IsDone always returns true.

        :param Elips:
        :type Elips: gp_Elips2d
        :param P1:
        :type P1: gp_Pnt2d
        :param P2:
        :type P2: gp_Pnt2d
        :param Sense: default value is Standard_True
        :type Sense: bool
        :rtype: None

        """
        _GCE2d.GCE2d_MakeArcOfEllipse_swiginit(self, _GCE2d.new_GCE2d_MakeArcOfEllipse(*args))

    def Value(self, *args):
        """
        * Returns the constructed arc of ellipse.

        :rtype: Handle_Geom2d_TrimmedCurve

        """
        return _GCE2d.GCE2d_MakeArcOfEllipse_Value(self, *args)


    def Operator(self, *args):
        """
        :rtype: Handle_Geom2d_TrimmedCurve

        """
        return _GCE2d.GCE2d_MakeArcOfEllipse_Operator(self, *args)


    def __del__(self):
    	try:
    		self.thisown = False
    		GarbageCollector.garbage.collect_object(self)
    	except:
    		pass


GCE2d_MakeArcOfEllipse.Value = new_instancemethod(_GCE2d.GCE2d_MakeArcOfEllipse_Value, None, GCE2d_MakeArcOfEllipse)
GCE2d_MakeArcOfEllipse.Operator = new_instancemethod(_GCE2d.GCE2d_MakeArcOfEllipse_Operator, None, GCE2d_MakeArcOfEllipse)
GCE2d_MakeArcOfEllipse._kill_pointed = new_instancemethod(_GCE2d.GCE2d_MakeArcOfEllipse__kill_pointed, None, GCE2d_MakeArcOfEllipse)
GCE2d_MakeArcOfEllipse_swigregister = _GCE2d.GCE2d_MakeArcOfEllipse_swigregister
GCE2d_MakeArcOfEllipse_swigregister(GCE2d_MakeArcOfEllipse)

class GCE2d_MakeArcOfHyperbola(GCE2d_Root):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        * Makes an arc of Hyperbola (TrimmedCurve from Geom2d) from a Hyperbola between two parameters Alpha1 and Alpha2.

        :param Hypr:
        :type Hypr: gp_Hypr2d
        :param Alpha1:
        :type Alpha1: float
        :param Alpha2:
        :type Alpha2: float
        :param Sense: default value is Standard_True
        :type Sense: bool
        :rtype: None

        * Makes an arc of Hyperbola (TrimmedCurve from Geom2d) from a Hyperbola between point <P> and the parameter Alpha.

        :param Hypr:
        :type Hypr: gp_Hypr2d
        :param P:
        :type P: gp_Pnt2d
        :param Alpha:
        :type Alpha: float
        :param Sense: default value is Standard_True
        :type Sense: bool
        :rtype: None

        * Makes an arc of Hyperbola (TrimmedCurve from Geom2d) from a Hyperbola between two points P1 and P2. Note: the orientation of the arc of hyperbola is: - the trigonometric sense if Sense is not defined or is true (default value), or - the opposite sense if Sense is false. - IsDone always returns true.

        :param Hypr:
        :type Hypr: gp_Hypr2d
        :param P1:
        :type P1: gp_Pnt2d
        :param P2:
        :type P2: gp_Pnt2d
        :param Sense: default value is Standard_True
        :type Sense: bool
        :rtype: None

        """
        _GCE2d.GCE2d_MakeArcOfHyperbola_swiginit(self, _GCE2d.new_GCE2d_MakeArcOfHyperbola(*args))

    def Value(self, *args):
        """
        * Returns the constructed arc of hyperbola.

        :rtype: Handle_Geom2d_TrimmedCurve

        """
        return _GCE2d.GCE2d_MakeArcOfHyperbola_Value(self, *args)


    def Operator(self, *args):
        """
        :rtype: Handle_Geom2d_TrimmedCurve

        """
        return _GCE2d.GCE2d_MakeArcOfHyperbola_Operator(self, *args)


    def __del__(self):
    	try:
    		self.thisown = False
    		GarbageCollector.garbage.collect_object(self)
    	except:
    		pass


GCE2d_MakeArcOfHyperbola.Value = new_instancemethod(_GCE2d.GCE2d_MakeArcOfHyperbola_Value, None, GCE2d_MakeArcOfHyperbola)
GCE2d_MakeArcOfHyperbola.Operator = new_instancemethod(_GCE2d.GCE2d_MakeArcOfHyperbola_Operator, None, GCE2d_MakeArcOfHyperbola)
GCE2d_MakeArcOfHyperbola._kill_pointed = new_instancemethod(_GCE2d.GCE2d_MakeArcOfHyperbola__kill_pointed, None, GCE2d_MakeArcOfHyperbola)
GCE2d_MakeArcOfHyperbola_swigregister = _GCE2d.GCE2d_MakeArcOfHyperbola_swigregister
GCE2d_MakeArcOfHyperbola_swigregister(GCE2d_MakeArcOfHyperbola)

class GCE2d_MakeArcOfParabola(GCE2d_Root):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        * Make an arc of Parabola (TrimmedCurve from Geom2d) from a Parabola between two parameters Alpha1 and Alpha2.

        :param Parab:
        :type Parab: gp_Parab2d
        :param Alpha1:
        :type Alpha1: float
        :param Alpha2:
        :type Alpha2: float
        :param Sense: default value is Standard_True
        :type Sense: bool
        :rtype: None

        * Make an arc of Parabola (TrimmedCurve from Geom2d) from a Parabola between point <P> and the parameter Alpha.

        :param Parab:
        :type Parab: gp_Parab2d
        :param P:
        :type P: gp_Pnt2d
        :param Alpha:
        :type Alpha: float
        :param Sense: default value is Standard_True
        :type Sense: bool
        :rtype: None

        * Make an arc of Parabola (TrimmedCurve from Geom2d) from a Parabola between two points P1 and P2. Please, note: the orientation of the arc of parabola is: - the trigonometric sense if Sense is not defined or is true (default value), or - the opposite sense if Sense is false. - IsDone always returns true.

        :param Parab:
        :type Parab: gp_Parab2d
        :param P1:
        :type P1: gp_Pnt2d
        :param P2:
        :type P2: gp_Pnt2d
        :param Sense: default value is Standard_True
        :type Sense: bool
        :rtype: None

        """
        _GCE2d.GCE2d_MakeArcOfParabola_swiginit(self, _GCE2d.new_GCE2d_MakeArcOfParabola(*args))

    def Value(self, *args):
        """
        * Returns the constructed arc of parabola.

        :rtype: Handle_Geom2d_TrimmedCurve

        """
        return _GCE2d.GCE2d_MakeArcOfParabola_Value(self, *args)


    def Operator(self, *args):
        """
        :rtype: Handle_Geom2d_TrimmedCurve

        """
        return _GCE2d.GCE2d_MakeArcOfParabola_Operator(self, *args)


    def __del__(self):
    	try:
    		self.thisown = False
    		GarbageCollector.garbage.collect_object(self)
    	except:
    		pass


GCE2d_MakeArcOfParabola.Value = new_instancemethod(_GCE2d.GCE2d_MakeArcOfParabola_Value, None, GCE2d_MakeArcOfParabola)
GCE2d_MakeArcOfParabola.Operator = new_instancemethod(_GCE2d.GCE2d_MakeArcOfParabola_Operator, None, GCE2d_MakeArcOfParabola)
GCE2d_MakeArcOfParabola._kill_pointed = new_instancemethod(_GCE2d.GCE2d_MakeArcOfParabola__kill_pointed, None, GCE2d_MakeArcOfParabola)
GCE2d_MakeArcOfParabola_swigregister = _GCE2d.GCE2d_MakeArcOfParabola_swigregister
GCE2d_MakeArcOfParabola_swigregister(GCE2d_MakeArcOfParabola)

class GCE2d_MakeCircle(GCE2d_Root):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        * creates a circle from a non persistent one.

        :param C:
        :type C: gp_Circ2d
        :rtype: None

        * A is the 'XAxis' of the circle which defines the origin of parametrization. It is not forbidden to create a circle with Radius = 0.0 The status is 'NegativeRadius' if Radius < 0.

        :param A:
        :type A: gp_Ax2d
        :param Radius:
        :type Radius: float
        :param Sense: default value is Standard_True
        :type Sense: bool
        :rtype: None

        * A is the local coordinate system of the circle which defines the origin of parametrization. It is not forbidden to create a circle with Radius = 0.0 The status is 'NegativeRadius' if Radius < 0.

        :param A:
        :type A: gp_Ax22d
        :param Radius:
        :type Radius: float
        :rtype: None

        * Make a Circle from Geom2d <TheCirc> parallel to another Circ <Circ> with a distance <Dist>. If Dist is greater than zero the result is enclosing the circle <Circ>, else the result is enclosed by the circle <Circ>.

        :param Circ:
        :type Circ: gp_Circ2d
        :param Dist:
        :type Dist: float
        :rtype: None

        * Make a Circle from Geom2d <TheCirc> parallel to another Circ <Circ> and passing through a Pnt <Point>.

        :param Circ:
        :type Circ: gp_Circ2d
        :param Point:
        :type Point: gp_Pnt2d
        :rtype: None

        * Make a Circ from gp <TheCirc> passing through 3 Pnt2d <P1>,<P2>,<P3>.

        :param P1:
        :type P1: gp_Pnt2d
        :param P2:
        :type P2: gp_Pnt2d
        :param P3:
        :type P3: gp_Pnt2d
        :rtype: None

        * Make a Circ from geom2d <TheCirc> by its center an radius.

        :param P:
        :type P: gp_Pnt2d
        :param Radius:
        :type Radius: float
        :param Sense: default value is Standard_True
        :type Sense: bool
        :rtype: None

        * Makes a Circle from geom2d <TheCirc> with its center <Center> and a point giving the radius. If Sense is true the local coordinate system of the solution is direct and non direct in the other case. Warning The MakeCircle class does not prevent the construction of a circle with a null radius. If an error occurs (that is, when IsDone returns false), the Status function returns: - gce_NegativeRadius if Radius is less than 0.0, or - gce_IntersectionError if points P1, P2 and P3 are collinear and the three are not coincident.

        :param Center:
        :type Center: gp_Pnt2d
        :param Point:
        :type Point: gp_Pnt2d
        :param Sense: default value is Standard_True
        :type Sense: bool
        :rtype: None

        """
        _GCE2d.GCE2d_MakeCircle_swiginit(self, _GCE2d.new_GCE2d_MakeCircle(*args))

    def Value(self, *args):
        """
        * Returns the constructed circle. Exceptions StdFail_NotDone if no circle is constructed.

        :rtype: Handle_Geom2d_Circle

        """
        return _GCE2d.GCE2d_MakeCircle_Value(self, *args)


    def Operator(self, *args):
        """
        :rtype: Handle_Geom2d_Circle

        """
        return _GCE2d.GCE2d_MakeCircle_Operator(self, *args)


    def __del__(self):
    	try:
    		self.thisown = False
    		GarbageCollector.garbage.collect_object(self)
    	except:
    		pass


GCE2d_MakeCircle.Value = new_instancemethod(_GCE2d.GCE2d_MakeCircle_Value, None, GCE2d_MakeCircle)
GCE2d_MakeCircle.Operator = new_instancemethod(_GCE2d.GCE2d_MakeCircle_Operator, None, GCE2d_MakeCircle)
GCE2d_MakeCircle._kill_pointed = new_instancemethod(_GCE2d.GCE2d_MakeCircle__kill_pointed, None, GCE2d_MakeCircle)
GCE2d_MakeCircle_swigregister = _GCE2d.GCE2d_MakeCircle_swigregister
GCE2d_MakeCircle_swigregister(GCE2d_MakeCircle)

class GCE2d_MakeEllipse(GCE2d_Root):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        * Creates an ellipse from a non persistent one from package gp

        :param E:
        :type E: gp_Elips2d
        :rtype: None

        * MajorAxis is the local coordinate system of the ellipse. It is the 'XAxis'. The minor axis is the YAxis of the ellipse. Sense give the sense of parametrization of the Ellipse. It is not forbidden to create an ellipse with MajorRadius = MinorRadius. The status is 'InvertRadius' if MajorRadius < MinorRadius or 'NegativeRadius' if MinorRadius < 0.

        :param MajorAxis:
        :type MajorAxis: gp_Ax2d
        :param MajorRadius:
        :type MajorRadius: float
        :param MinorRadius:
        :type MinorRadius: float
        :param Sense: default value is Standard_True
        :type Sense: bool
        :rtype: None

        * Axis is the local coordinate system of the ellipse. It is not forbidden to create an ellipse with MajorRadius = MinorRadius. The status is 'InvertRadius' if MajorRadius < MinorRadius or 'NegativeRadius' if MinorRadius < 0.

        :param Axis:
        :type Axis: gp_Ax22d
        :param MajorRadius:
        :type MajorRadius: float
        :param MinorRadius:
        :type MinorRadius: float
        :rtype: None

        * Make an Ellipse centered on the point Center, where - the major axis of the ellipse is defined by Center and S1, - its major radius is the distance between Center and S1, and - its minor radius is the distance between S2 and the major axis. The implicit orientation of the ellipse is: - the sense defined by Axis or E, - the sense defined by points Center, S1 and S2, - the trigonometric sense if Sense is not given or is true, or - the opposite sense if Sense is false.

        :param S1:
        :type S1: gp_Pnt2d
        :param S2:
        :type S2: gp_Pnt2d
        :param Center:
        :type Center: gp_Pnt2d
        :rtype: None

        """
        _GCE2d.GCE2d_MakeEllipse_swiginit(self, _GCE2d.new_GCE2d_MakeEllipse(*args))

    def Value(self, *args):
        """
        * Returns the constructed ellipse. Exceptions StdFail_NotDone if no ellipse is constructed.

        :rtype: Handle_Geom2d_Ellipse

        """
        return _GCE2d.GCE2d_MakeEllipse_Value(self, *args)


    def Operator(self, *args):
        """
        :rtype: Handle_Geom2d_Ellipse

        """
        return _GCE2d.GCE2d_MakeEllipse_Operator(self, *args)


    def __del__(self):
    	try:
    		self.thisown = False
    		GarbageCollector.garbage.collect_object(self)
    	except:
    		pass


GCE2d_MakeEllipse.Value = new_instancemethod(_GCE2d.GCE2d_MakeEllipse_Value, None, GCE2d_MakeEllipse)
GCE2d_MakeEllipse.Operator = new_instancemethod(_GCE2d.GCE2d_MakeEllipse_Operator, None, GCE2d_MakeEllipse)
GCE2d_MakeEllipse._kill_pointed = new_instancemethod(_GCE2d.GCE2d_MakeEllipse__kill_pointed, None, GCE2d_MakeEllipse)
GCE2d_MakeEllipse_swigregister = _GCE2d.GCE2d_MakeEllipse_swigregister
GCE2d_MakeEllipse_swigregister(GCE2d_MakeEllipse)

class GCE2d_MakeHyperbola(GCE2d_Root):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        * Creates an Hyperbola from a non persistent one from package gp

        :param H:
        :type H: gp_Hypr2d
        :rtype: None

        * MajorAxis is the 'XAxis' of the hyperbola. The major radius of the hyperbola is on this 'XAxis' and the minor radius is on the 'YAxis' of the hyperbola. The status is 'NegativeRadius' if MajorRadius < 0.0 or if MinorRadius < 0.0

        :param MajorAxis:
        :type MajorAxis: gp_Ax2d
        :param MajorRadius:
        :type MajorRadius: float
        :param MinorRadius:
        :type MinorRadius: float
        :param Sense:
        :type Sense: bool
        :rtype: None

        * Axis is the local coordinate system of the hyperbola. The major radius of the hyperbola is on this 'XAxis' and the minor radius is on the 'YAxis' of the hyperbola. The status is 'NegativeRadius' if MajorRadius < 0.0 or if MinorRadius < 0.0

        :param Axis:
        :type Axis: gp_Ax22d
        :param MajorRadius:
        :type MajorRadius: float
        :param MinorRadius:
        :type MinorRadius: float
        :rtype: None

        * Creates a hyperbol centered on the origin of the coordinate system Axis, with major and minor radii MajorRadius and MinorRadius, where the major axis is the 'X Axis' of Axis (Axis is the local coordinate system of the hyperbola). The implicit orientation of the ellipse is: - the sense defined by Axis or H, - the sense defined by points Center, S1 and S2, - the trigonometric sense if Sense is not given or is true, or - the opposite sense if Sense is false. Warning If an error occurs (that is, when IsDone returns false), the Status function returns: - gce_NegativeRadius if MajorRadius or MinorRadius is less than 0.0, or - gce_InvertAxis if the major radius defined by Center and S1 is less than the minor radius defined by Center, S1 and S2.Make an Hyperbola with its center and two apexes.

        :param S1:
        :type S1: gp_Pnt2d
        :param S2:
        :type S2: gp_Pnt2d
        :param Center:
        :type Center: gp_Pnt2d
        :rtype: None

        """
        _GCE2d.GCE2d_MakeHyperbola_swiginit(self, _GCE2d.new_GCE2d_MakeHyperbola(*args))

    def Value(self, *args):
        """
        * Returns the constructed hyperbola. Exceptions: StdFail_NotDone if no hyperbola is constructed.

        :rtype: Handle_Geom2d_Hyperbola

        """
        return _GCE2d.GCE2d_MakeHyperbola_Value(self, *args)


    def Operator(self, *args):
        """
        :rtype: Handle_Geom2d_Hyperbola

        """
        return _GCE2d.GCE2d_MakeHyperbola_Operator(self, *args)


    def __del__(self):
    	try:
    		self.thisown = False
    		GarbageCollector.garbage.collect_object(self)
    	except:
    		pass


GCE2d_MakeHyperbola.Value = new_instancemethod(_GCE2d.GCE2d_MakeHyperbola_Value, None, GCE2d_MakeHyperbola)
GCE2d_MakeHyperbola.Operator = new_instancemethod(_GCE2d.GCE2d_MakeHyperbola_Operator, None, GCE2d_MakeHyperbola)
GCE2d_MakeHyperbola._kill_pointed = new_instancemethod(_GCE2d.GCE2d_MakeHyperbola__kill_pointed, None, GCE2d_MakeHyperbola)
GCE2d_MakeHyperbola_swigregister = _GCE2d.GCE2d_MakeHyperbola_swigregister
GCE2d_MakeHyperbola_swigregister(GCE2d_MakeHyperbola)

class GCE2d_MakeLine(GCE2d_Root):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        * Creates a line located in 2D space with the axis placement A. The Location of A is the origin of the line.

        :param A:
        :type A: gp_Ax2d
        :rtype: None

        * Creates a line from a non persistent line from package gp.

        :param L:
        :type L: gp_Lin2d
        :rtype: None

        * P is the origin and V is the direction of the line.

        :param P:
        :type P: gp_Pnt2d
        :param V:
        :type V: gp_Dir2d
        :rtype: None

        * Make a Line from Geom2d <TheLin> parallel to another Lin <Lin> and passing through a Pnt <Point>.

        :param Lin:
        :type Lin: gp_Lin2d
        :param Point:
        :type Point: gp_Pnt2d
        :rtype: None

        * Make a Line from Geom2d <TheLin> parallel to another Lin <Lin> at a distance <Dist>.

        :param Lin:
        :type Lin: gp_Lin2d
        :param Dist:
        :type Dist: float
        :rtype: None

        * Make a Line from Geom2d <TheLin> passing through 2 Pnt <P1>,<P2>. It returns false if <p1> and <P2> are confused. Warning If points P1 and P2 coincident (that is, when IsDone returns false), the Status function returns gce_ConfusedPoints.

        :param P1:
        :type P1: gp_Pnt2d
        :param P2:
        :type P2: gp_Pnt2d
        :rtype: None

        """
        _GCE2d.GCE2d_MakeLine_swiginit(self, _GCE2d.new_GCE2d_MakeLine(*args))

    def Value(self, *args):
        """
        * Returns the constructed line. Exceptions StdFail_NotDone if no line is constructed.

        :rtype: Handle_Geom2d_Line

        """
        return _GCE2d.GCE2d_MakeLine_Value(self, *args)


    def Operator(self, *args):
        """
        :rtype: Handle_Geom2d_Line

        """
        return _GCE2d.GCE2d_MakeLine_Operator(self, *args)


    def __del__(self):
    	try:
    		self.thisown = False
    		GarbageCollector.garbage.collect_object(self)
    	except:
    		pass


GCE2d_MakeLine.Value = new_instancemethod(_GCE2d.GCE2d_MakeLine_Value, None, GCE2d_MakeLine)
GCE2d_MakeLine.Operator = new_instancemethod(_GCE2d.GCE2d_MakeLine_Operator, None, GCE2d_MakeLine)
GCE2d_MakeLine._kill_pointed = new_instancemethod(_GCE2d.GCE2d_MakeLine__kill_pointed, None, GCE2d_MakeLine)
GCE2d_MakeLine_swigregister = _GCE2d.GCE2d_MakeLine_swigregister
GCE2d_MakeLine_swigregister(GCE2d_MakeLine)

class GCE2d_MakeParabola(GCE2d_Root):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        * Creates a parabola from a non persistent one.

        :param Prb:
        :type Prb: gp_Parab2d
        :rtype: None

        * Creates a parabola with its local coordinate system and it's focal length 'Focal'. The 'Location' point of 'Axis' is the vertex of the parabola Status is 'NegativeFocusLength' if Focal < 0.0

        :param Axis:
        :type Axis: gp_Ax22d
        :param Focal:
        :type Focal: float
        :rtype: None

        * Creates a parabola with its 'MirrorAxis' and it's focal length 'Focal'. MirrorAxis is the axis of symmetry of the curve, it is the 'XAxis'. The 'YAxis' is parallel to the directrix of the parabola. The 'Location' point of 'MirrorAxis' is the vertex of the parabola Status is 'NegativeFocusLength' if Focal < 0.0

        :param MirrorAxis:
        :type MirrorAxis: gp_Ax2d
        :param Focal:
        :type Focal: float
        :param Sense:
        :type Sense: bool
        :rtype: None

        * Creates a parabola with the local coordinate system and the focus point. The sense of parametrization is given by Sense.

        :param D:
        :type D: gp_Ax22d
        :param F:
        :type F: gp_Pnt2d
        :rtype: None

        * D is the directrix of the parabola and F the focus point. The symmetry axis 'XAxis' of the parabola is normal to the directrix and pass through the focus point F, but its 'Location' point is the vertex of the parabola. The 'YAxis' of the parabola is parallel to D and its 'Location' point is the vertex of the parabola.

        :param D:
        :type D: gp_Ax2d
        :param F:
        :type F: gp_Pnt2d
        :param Sense: default value is Standard_True
        :type Sense: bool
        :rtype: None

        * Make a parabola with focal point S1 and center O The branch of the parabola returned will have <S1> as focal point The implicit orientation of the parabola is: - the same one as the parabola Prb, - the sense defined by the coordinate system Axis or the directrix D, - the trigonometric sense if Sense is not given or is true, or - the opposite sense if Sense is false. Warning The MakeParabola class does not prevent the construction of a parabola with a null focal distance. If an error occurs (that is, when IsDone returns false), the Status function returns: - gce_NullFocusLength if Focal is less than 0.0, or - gce_NullAxis if points S1 and O are coincident.

        :param S1:
        :type S1: gp_Pnt2d
        :param O:
        :type O: gp_Pnt2d
        :rtype: None

        """
        _GCE2d.GCE2d_MakeParabola_swiginit(self, _GCE2d.new_GCE2d_MakeParabola(*args))

    def Value(self, *args):
        """
        * Returns the constructed parabola. Exceptions StdFail_NotDone if no parabola is constructed.

        :rtype: Handle_Geom2d_Parabola

        """
        return _GCE2d.GCE2d_MakeParabola_Value(self, *args)


    def Operator(self, *args):
        """
        :rtype: Handle_Geom2d_Parabola

        """
        return _GCE2d.GCE2d_MakeParabola_Operator(self, *args)


    def __del__(self):
    	try:
    		self.thisown = False
    		GarbageCollector.garbage.collect_object(self)
    	except:
    		pass


GCE2d_MakeParabola.Value = new_instancemethod(_GCE2d.GCE2d_MakeParabola_Value, None, GCE2d_MakeParabola)
GCE2d_MakeParabola.Operator = new_instancemethod(_GCE2d.GCE2d_MakeParabola_Operator, None, GCE2d_MakeParabola)
GCE2d_MakeParabola._kill_pointed = new_instancemethod(_GCE2d.GCE2d_MakeParabola__kill_pointed, None, GCE2d_MakeParabola)
GCE2d_MakeParabola_swigregister = _GCE2d.GCE2d_MakeParabola_swigregister
GCE2d_MakeParabola_swigregister(GCE2d_MakeParabola)

class GCE2d_MakeSegment(GCE2d_Root):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        * Make a segment of Line from the 2 points <P1> and <P2>. Status is 'ConfusedPoints' if <P1> and <P2> are confused.

        :param P1:
        :type P1: gp_Pnt2d
        :param P2:
        :type P2: gp_Pnt2d
        :rtype: None

        * Make a segment of Line from the point <P1> with the direction <P> and ended by the projection of <P2> on the line <P1,V>. Status is 'ConfusedPoints' if <P1> and <P2> are confused.

        :param P1:
        :type P1: gp_Pnt2d
        :param V:
        :type V: gp_Dir2d
        :param P2:
        :type P2: gp_Pnt2d
        :rtype: None

        * Make a segment of Line from the line <Line> between the two parameters U1 and U2. Status is 'SameParamters' if <U1> is equal <U2>.

        :param Line:
        :type Line: gp_Lin2d
        :param U1:
        :type U1: float
        :param U2:
        :type U2: float
        :rtype: None

        * Make a segment of Line from the line <Line> between the point <Point> and the parameter Ulast. It returns NullObject if <U1> is equal <U2>.

        :param Line:
        :type Line: gp_Lin2d
        :param Point:
        :type Point: gp_Pnt2d
        :param Ulast:
        :type Ulast: float
        :rtype: None

        * Make a segment of Line from the line <Line> between the two points <P1> and <P2>. It returns NullObject if <P1> and <P2> are confused. Warning If the points which limit the segment are coincident for given points or for the projection of given points on the line which supports the line segment (that is, when IsDone returns false), the Status function returns gce_ConfusedPoints. This warning only concerns the first two constructors.

        :param Line:
        :type Line: gp_Lin2d
        :param P1:
        :type P1: gp_Pnt2d
        :param P2:
        :type P2: gp_Pnt2d
        :rtype: None

        """
        _GCE2d.GCE2d_MakeSegment_swiginit(self, _GCE2d.new_GCE2d_MakeSegment(*args))

    def Value(self, *args):
        """
        * Returns the constructed line segment. Exceptions StdFail_NotDone if no line segment is constructed.

        :rtype: Handle_Geom2d_TrimmedCurve

        """
        return _GCE2d.GCE2d_MakeSegment_Value(self, *args)


    def Operator(self, *args):
        """
        :rtype: Handle_Geom2d_TrimmedCurve

        """
        return _GCE2d.GCE2d_MakeSegment_Operator(self, *args)


    def __del__(self):
    	try:
    		self.thisown = False
    		GarbageCollector.garbage.collect_object(self)
    	except:
    		pass


GCE2d_MakeSegment.Value = new_instancemethod(_GCE2d.GCE2d_MakeSegment_Value, None, GCE2d_MakeSegment)
GCE2d_MakeSegment.Operator = new_instancemethod(_GCE2d.GCE2d_MakeSegment_Operator, None, GCE2d_MakeSegment)
GCE2d_MakeSegment._kill_pointed = new_instancemethod(_GCE2d.GCE2d_MakeSegment__kill_pointed, None, GCE2d_MakeSegment)
GCE2d_MakeSegment_swigregister = _GCE2d.GCE2d_MakeSegment_swigregister
GCE2d_MakeSegment_swigregister(GCE2d_MakeSegment)



